add tito widget when button is clicked
simplabs/ember-pro-workshop pull request #7
Opened 2017-12-20 12:07 UTC by trabaldini

closes #3

2017-12-20 12:12 UTC, marcoow requested changes
I don't think this is the correct way to do this - see e.g. https://github.com/emberfest/emberfest.github.io/commit/84e42e3ad9592906b84681de92321fe6d3c78eea for an example

2017-12-20 12:52 UTC, trabaldini commented
this should work correctly now?

2017-12-20 13:02 UTC, marcoow reviewed
see https://github.com/simplabs/ember-basics-workshop/pull/11#pullrequestreview-84754946

2017-12-21 19:08 UTC, marcoow approved these changes

2017-12-21 19:08 UTC, merged